### ISSUE TITLE
Migrate to NASA-DEVELOP account

### ISSUE THREAD

**Issue by Jwely** [NASA-DEVELOP/VOCAL#58]
I expect we will get a paid plan for some private repos by Monday evening. At that point you should have the authority required to change VOCAL ownership to [nasa develop](https://github.com/NASA-DEVELOP). If you wish, you can brand your repo in some way with this [tiny DEVELOP logo](https://github.com/NASA-DEVELOP/dnppy/blob/master/docs/source/tiny_develop_logo_solid.png) that will also be used on our AGOL maps.

**Comment by stapleCamel** [comment]
Looks its been said and done. It would have been nice if all the relevant parties were informed when this migration occurred.
